Assignments/sudoku
bhs-intro-to-programming/SadieBurris pull request #13
Opened 2022-11-09 23:31 UTC by SadieBurris

I spent almost the entire time working on something I realized was stupid so I deleted it. :(
Anyway heres what I have

2022-11-10 04:32 UTC, gigamonkey reviewed
Yeah, that's sometimes how it goes. Hope it wasn't too frustrating. Thanks for making the PR anyway.

2022-11-10 23:30 UTC, SadieBurris commented
again a very unproductive day, this time because Im oddly tired. Sorry :(

2022-11-13 05:37 UTC, gigamonkey reviewed
Tired or not, you made some good progress. I left a few comments about ways you can structure your data to make the code more clear.

2022-11-13 05:37 UTC, gigamonkey commented on assignments/sudoku/code.js
> +    }
Took me a sec to figure out what this was doing. Now that I see it I'd say it'd be clearer to break this out to a separate function, maybe something like `drawNumberMenu` or something with it's own loop to draw the numbers.

Then you can decide if you want to call that function from `drawBoard1st` or maybe just add a call to the new function at the place you currently call `drawBoard1st`. The argument for the latter approach is that it's good to make functions that are "cohesive" meaning they do just one thing and do it well. `drawBoard1st` should probably be responsible for just drawing the actual board. And drawing the numbers can be separate from that since it's really a separate thing. (You can imagine, for instance, building a sudoku game that doesn't have the same number menu but almost certainly will have the board.)

2022-11-13 05:37 UTC, gigamonkey commented on assignments/sudoku/code.js
> +    }
I'm not quite sure what's going on here. I'm guessing this is intended to track the number that have been used elsewhere in the row and column (and later you're going to add the box, I guess, based on the functions below).  I'm further guessing this is heading somewhere that you'll be able to disallow illegal placements in a given square?

If so, that's pretty clever. However it might be a good place so use an object rather than an array with a sort of magic structure. (I'm assuming element 0 is always the number that has actually been placed in the square or `''` if nothing has been yet and the rest of the array is the numbers that have been placed elsewhere in the rows, columns, and boxes. It might be clearer to instead use an object like:

```javascript
{
  placed: 9,
  usedElsewhere: [8, 7, 1, 3]
}
```

Then line 22 above becomes:

```javascript
b[row][col].placed = selected
```

and these lines become:

```javascript
b[row][i].usedElsewhere.push(selected)
b[i][col].usedElsewhere.push(selected)
```

and then it's really clear what's going on.

2022-11-13 05:37 UTC, gigamonkey commented on assignments/sudoku/code.js
> +      if (b[j][i].length === 9 && b[j][i][0] === '') {
This code also will become clearer if you use something like the object I suggested above.

2022-11-13 05:37 UTC, gigamonkey commented on assignments/sudoku/code.js
> +const lineNine = () => {
I like where this is going.

2022-11-18 23:32 UTC, SadieBurris commented
still not done

2022-11-20 22:45 UTC, gigamonkey requested changes
So rather than leave line-by-line comments here I got inspired to use this code to demonstrate more fully how I'd go about simplifying some code and made a screencast which you can see here: https://vimeo.com/773114443

(I've also put that screencast in Classroom for everyone to watch;  as you'll see I did not identify the author of the code in the video though I'm happy to credit you if you'd like.)

Anyway, keep going. This is great. While the changes I make in the video, are somewhat extensive by the end, all they really do is reveal the good structure that you have here already. I've done much more dramatic cleanups of code written by much more experience programmers than you and found much less well structured ideas underneath.

2022-11-21 06:35 UTC, SadieBurris commented
What I have found myself doing more and more is writing code that makes sense to me throughout the process, and then when Im finished I change it to make sense to others as well. I was planning to make something like this, however I wanted to finish it first. (I personally prefer i and j vs row and col)

2022-11-21 17:13 UTC, gigamonkey commented
Yeah, that's a very common cycle—the make it work, then make it clear loop. I also find that making things as clear as possible helps *me* to do the next thing by decreasing the cognitive load of understanding my own code so I tend to operate in a pretty tight loop of, write a little bit of code and then tidy it up and then write a little more. Not saying that's the only way to do it but it works for me. Also, I made the video because learning to simplify code is something everyone who's working on more complex programs needs to get used to and your code was complex enough that the simplifications were actually somewhat interesting.

As to `i` and `j` vs `row` and `col`, I'd say it doesn't matter which you choose but you should probably be consistent so use `i` and `j` everywhere or `row` and `col` everywhere. And if you use `i` and `j` as the main indices into the main dimensions of the board don't use those names for other loop variables.

2022-12-05 23:30 UTC, SadieBurris commented
Not done, and doesnt work (yet hopefully)

2022-12-06 04:24 UTC, gigamonkey requested changes
Hey, I just made a place for you to put this:

https://intro.gigamonkeys.com/assignments/maze-solver/

Tomorrow (today? Tuesday anyway) why don't you move the relevant code there and let's talk about how you're approaching this. I realize you've been off on your own for probably longer than is fair.

2022-12-09 22:39 UTC, SadieBurris commented
I moved the other code, so now its just sudoku

2022-12-11 17:13 UTC, gigamonkey approved these changes
This looks good. I opened a PR that you can merge into this branch if you want that adds some code for setting up puzzles—anyway, it's all described in that PR.

If you want to wait until Monday, we can walk you merging that into this and then this into `main`. (Yeah, git can be kinda confusing. Powerful but confusing.)

2022-12-13 23:27 UTC, SadieBurris commented
As you can see its going so very well (sarcasm if you couldnt notice)

2022-12-14 05:45 UTC, gigamonkey commented
I'm just going to comment here because if I actually review it it puts it back into a state where you have to do something to keep it from counting against your Github grade. So this will be waiting for you to work on on Friday. Good luck with the rest of your exams.

2022-12-30 04:30 UTC, gigamonkey approved these changes
I'm approving this now to get it out of my queue of things to review. You should probably merge this as it is; you can always pick it back up later.

2023-01-03 22:59 UTC, merged