Assignments/2048
bhs-intro-to-programming/SadieBurris pull request #15
Opened 2022-12-09 23:33 UTC by SadieBurris

Still working on it. Trying to check if something in undefined and its being annoying

2022-12-10 01:40 UTC, gigamonkey requested changes
Request changes only in the sense of "carry on".

2022-12-10 01:40 UTC, gigamonkey commented on assignments/2048/code.js
> +    if (b[row][col + i] !== undefined) {
I don't think `b[r][c]` is going to be undefined for any legal indices `r` and `c` since you made a three level array: with the third level consisting of two-element arrays with undefined values.

2022-12-16 20:40 UTC, SadieBurris commented
Im working on Snake Game

2022-12-30 03:21 UTC, gigamonkey approved these changes
This is a great start. Look forward to seeing you wire it into the animation framework. You should go ahead and merge this so next time I review it I see what's changed since now.

2022-12-30 03:21 UTC, gigamonkey commented on assignments/2048/code.js
> +  if (firstTime === true) {
Remember, you never need to compare a boolean expression to a boolean literal:

```javascript
  if (firstTime) {
```

is plenty.

2022-12-30 03:21 UTC, gigamonkey commented on assignments/2048/code.js
> +const b = Array(numOfSquares).fill().map(() => Array(numOfSquares).fill().map(() => Array(2).fill(0)))
You still love those two-element arrays I see. I'll continue to encourage you to use objects, i.e. something like:

```javascript
const b = Array(numOfSquares).fill().map(() => Array(numOfSquares).fill().map(() => ({snake: 0, apple: false})));
```

But that advice will probably on make sense to you someday when you come back to some of your on code and find yourself trying to remember what 0 and 1 mean rather than nice names like `snake` and `apple`. Until then, this is fine.

2023-01-03 22:59 UTC, merged