End of class
bhs-intro-to-programming/SadieBurris pull request #26
Opened 2023-01-12 23:31 UTC by SadieBurris

2023-01-12 23:31 UTC, SadieBurris commented
Spent most of today looking for a repl

2023-01-13 04:09 UTC, gigamonkey approved these changes

2023-01-13 04:10 UTC, gigamonkey commented
Did the Chrome REPL serve your needs? Depending what you're trying to do, it might or might not.

2023-01-14 02:30 UTC, gigamonkey approved these changes
More good progress.

2023-01-14 02:30 UTC, gigamonkey commented on projects/boids/public/script.js
> +const distance = (x1, y1, x2, y2) => Math.sqrt((x1 - x2) ** 2 + (y1 - y2) ** 2)
Since your boids are objects with `x` and `y` properties, you can simplify this function and all the places you call it by having it take two objects as arguments and then get the `x` and `y` of each of them.

Also, although I made you write this function on past assessments there's actually a function in the Math library that does most of the math: `Math.hypot(a, b)` returns the hypotenuse of a triangle with sides `a` and `b`. So I'd keep this function to handle the pulling out the `x` and `y` properties and doing the subtraction but let `hypot` take care of the squaring, summing, and squarerooting part.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot

2023-01-14 02:30 UTC, gigamonkey commented on projects/boids/public/script.js
> +            if (distance(locs[i].x, locs[i].y, locs[boidNum].x, locs[boidNum].y) < 100 && boidNum !== i) {
This is kind of a subtle point (and not something I've talked about as far as I recall) but since `&&` (and also `||`) do what's called "short circuiting" meaning they only evaluate as much as they need to, to determine the final value of the expression, you can sometimes make code more efficient by the order of the expressions. In this case checking `boidNum !== i` is going to be much cheaper than the call to `distance` so it'd be slightly nicer to check it first. That way, when it's false you won't waste any time computing a distance that is going to be irrelevant.

2023-01-28 18:23 UTC, gigamonkey approved these changes
Seems like you're heading in the right direction. I'll save up my style suggestions until you get to a point where you want to stop dealing with the basic functionality for a while; I can tell you're in the "get it working" phase now.

P.S. If you keep this PR open (which is fine) can you edit the title of the PR (click the Edit button next to the PR title near the top of the page) to make it something more descriptive about what's in the PR than "End of class". That makes it easier for me to see what's going on when I look at a big list of PRs.

2023-01-28 18:23 UTC, gigamonkey commented on projects/boids/public/script.js
> +}//middle of smthn not done with this yet so no judgement
Oki-doke.

2023-01-31 01:54 UTC, gigamonkey approved these changes
Glad you got it to a point where it's doing something. That's always a great milestone. Carry on. (Regarding your comment at line 5 about dividing the area into sectors, it sounds like you're part way to re-inventing quad trees, a data structure to aid in things like collision detection. If you want to read about them, this is a pretty good quick summary I found: https://gamedevelopment.tutsplus.com/tutorials/quick-tip-use-quadtrees-to-detect-likely-collisions-in-2d-space--gamedev-374)

2023-01-31 01:54 UTC, gigamonkey commented on projects/boids/public/script.js
>      totalY /= locs[boidNum].nearby.length
Is every boid's `nearby` guaranteed to contain at least one element (e.g. if boids are in their own `nearby` list)? If not then `nearby.length` could be 0 and this will give you 0. Which is maybe what the condition at line 45 is about? (Hmmm, seems like it can be empty since the boid is explicitly excluded from its own list.)

2023-01-31 01:54 UTC, gigamonkey commented on projects/boids/public/script.js
> +    }
It feels like everything up to here in this function is basically computing the average position of all the boids in the `nearby` list. If I've got that right, it might make things more clear to break it out as a separate function (`averagePosition` or whatever) that maybe takes an array of boids and returns the average position as an `{x, y}` object. Then this function can just call that function to get the object used in the next line. One of the clues that maybe there's a hidden function is that all these lines are really operating on `locs[boidNum].nearby`.

In general breaking out bits of functionality into named functions is helpful because then the reader has two clues what the code does: the name of the function and the code itself. But assuming they are both right it's easier to se that a function called `averagePosition` in fact computes that than it is to read a bunch of unnamed code and figure out that that's what it does.

2023-01-31 22:35 UTC, SadieBurris commented on projects/boids/public/script.js
> +    if(totalX * 0 !== 0) {
yeah thats kinda the point if there is no nearby neghbors it returns as NaN so this is to check if its a number (if there is a neighbor)

2023-02-01 04:25 UTC, gigamonkey approved these changes
Glad to see you're making progress, even when your brain is shutting down. (It's a pity that we always have to have this class 6th period.)

2023-02-01 04:25 UTC, gigamonkey commented on projects/boids/public/script.js
> +const totals = []
Rather than declare this as a global variable, it seems like you can create it in `aOC` and return it from that function. In general avoiding globals makes code easier to understand because a function that is written entirely in terms of its arguments and local variables can be understood in isolation whereas if it depends on globals then you have to worry about what other code might be doing things to those globals.

2023-02-01 04:25 UTC, gigamonkey commented on projects/boids/public/script.js
> +    totals[1] /= locs[boidNum].nearby.length
I feel like these two lines belong in `aOC` since they're part of the computing the average. And then, if you take my advice from line 4, you might want to have `aOC` take care of wrapping up the return values as an object with `{x,y}` properties since that's what you'll need anyway to pass to `distance` and `totals.x` is as easier, or easier to write and read than `totals[0]`.

2023-02-02 01:25 UTC, gigamonkey requested changes
Some of the comments I've left previously still apply. I'll let you address them (or not) at your leisure. Otherwise, carry on.

2023-02-03 04:00 UTC, gigamonkey approved these changes
I left a couple comments about some of the things that may be causing your boids to combust. It took me some poking around and messing with the code to debug it, though. If you want I can show you some tricks of how I did it either live or maybe in a screen cast. Or you can keep banging your head against it and figure out your own set of tricks. Whatever suits you.

2023-02-03 05:02 UTC, gigamonkey commented
Oh, I also found this thing which has a good summary of the three basic Boid mechanisms. 

https://www.cs.cmu.edu/afs/cs/academic/class/15462-s10/www/lec-slides/Lecture24_flocking.pdf

You don't have to invent everything from scratch; it's totally fine to find something like this and then spend your mental energy on figuring out how to translate it into code.

2023-02-03 22:36 UTC, SadieBurris commented on projects/boids/public/script.js
> +    totalY /= locs[boidNum].nearby.length
yeah ik thats why I have the * 0 !== 0 thing so if it has no neighbors it goes to a random spot. Just a temp thing but still.

2023-02-03 23:32 UTC, SadieBurris commented
The boids REALLY REALLY like the top left corner. Its infuriating. Also they no longer spontaniously combust and instead have a heart attack, but at least I know why that is.

2023-02-07 17:17 UTC, gigamonkey reviewed
It's possible that I this project was a trap in that to do it properly may require knowing some trigonometry. I now know that isn't covered in math class until sophomore year so unless you've learned it for some reason outside of school you may be missing some key knowledge that would make this project much easier. If you want, I can give you a crash course; I'm sure you can pick up the few bits you need for this pretty quickly.

I also think you may want to reset a bit and simplify the program—for instance, can you animate one boid so that it flies around at random and maybe stays away from the walls. Then when you've got that working, add multiple boids that are unaware of each other's existence. Then add in some other forces. The whole thing is probably too much to bite off all at once—anyway, it was for me. Let's talk today about how you want to tackle this so you  can get unmired and have this be less painful.

2023-02-08 01:46 UTC, gigamonkey approved these changes
This is good. I ran it and it's doing a thing that I'm guessing is more or less what you wanted it to do: the boid flies around and turns before it hits a wall. Now you can build from here!

2023-02-08 01:46 UTC, gigamonkey commented on projects/boids/public/script.js
> +const noTimeLTP = () => {
just a comment, not a criticism, but I'm trying to guess what LTP stands for and totally failing.

2023-02-08 03:50 UTC, SadieBurris commented on projects/boids/public/script.js
> +const noTimeLTP = () => {
"Like the present," I just didnt want to need to write it out every time.

2023-02-09 04:07 UTC, gigamonkey approved these changes
Hey, they go on vacation but they come back! I take it from one of your commit messages that your Dad is kibitzing. Which is fine if you like the help. But if you want him off your back tell him I'll give him his own assignment to keep him busy. ;-)

2023-02-09 04:07 UTC, gigamonkey commented on projects/boids/public/script.js
> +const noTimeLTP = () => {
Got it!

2023-02-10 03:28 UTC, gigamonkey approved these changes
Looks good. See you on Tuesday.

2023-03-02 23:29 UTC, merged