End of Class, almost done
bhs-intro-to-programming/SadieBurris pull request #28
Opened 2023-01-18 23:34 UTC by SadieBurris

2023-01-19 04:13 UTC, gigamonkey requested changes
Yup. Nearly done. Have you checked it in the browser. There's a little glitch in the list item about `<h1>` to `<h6>` items. I wonder if you can figure out what's going on there? (That code was in your earlier PR; I didn't notice it then.)

2023-01-20 01:14 UTC, gigamonkey requested changes
The two new functions are very much the kind of thing I was thinking of. I want to make sure you understand the point about `varName` not doing what you think it is. So can you change that and then re-request review? Also happy to chat about it if you don't see it.

2023-01-20 01:14 UTC, gigamonkey commented on projects/2023-01-17/public/scripts/script.js
> +const makeText = (type, varName, text) => {
The `varName` argument isn't doing what you think it is, I don't think. Think about what, if anything, would change if you just got rid of it and added a `const` in front of `varName` on line 5.

2023-01-20 01:14 UTC, gigamonkey commented on projects/2023-01-17/public/scripts/script.js
> +  a3List.append(varName)
This works, and in the context of this assignment is probably fine. In general it might be better to pass in the list element you want to add the `li` to as it would make the function more generally useful. But it's also fine to not generalize until you need to. Just something to think about.

2023-01-20 22:38 UTC, SadieBurris commented on projects/2023-01-17/public/scripts/script.js
> +  a3List.append(varName)
Yeah I was going to but class ended

2023-01-21 20:39 UTC, gigamonkey approved these changes
Nice.

2023-01-23 22:49 UTC, merged