Projects/hopefully physics
bhs-intro-to-programming/SadieBurris pull request #35
Opened 2023-03-03 23:31 UTC by SadieBurris

2023-03-07 16:39 UTC, gigamonkey approved these changes
Looks good. Do you know why the bouncing damps out? I don't see anything in the math that looks like it's causing it but maybe I'm missing something. Did you mean for that to happen?

2023-03-15 03:06 UTC, gigamonkey approved these changes
Keep going I guess. As I said in one of my comments below, I'd be happy to talk with you about this code but just reading it, I can't grok it well enough to make any particularly useful suggestions.

2023-03-15 03:06 UTC, gigamonkey commented on projects/hopefully-physics/public/script.js
> +        //worked until I tried to fix something else AND NOW ITS BROKEN AGAIN
Not gonna lie. This code hurts my brain a bit. So it's hard for me to give useful comments here since I'm not sure quite what the goal is. But I'm sure you'll power through. Happy to talk though any part of it during class, if you want.

2023-03-15 03:06 UTC, gigamonkey commented on projects/hopefully-physics/public/script.js
> +        obs[i].c[j].num = -1
I'm curious what the motivation for this change was. Seems like the earlier version would have been simpler to deal with but I'm also not fully understanding everything that's going on in this code.

2023-03-16 04:04 UTC, gigamonkey requested changes
So I found a thing that I have to imagine is causing at least some of your pain. Hopefully after you fix that, things'll fall into place a bit better.

2023-03-16 04:04 UTC, gigamonkey commented on projects/hopefully-physics/public/script.js
> +    obs.push({ pos: { x: Math.random() * width, y: Math.random() * height }, r: Math.random() * 40 + 10, a: { x: 0, y: 0.5 }, v: { x: Math.random() * 5, y: 0 }, c: Array(num).fill({ num: false, curC:
Oh no. I think I just saw what may be your problem. When you use `fill` on an array it fills the array with the value you give it, meaning every element of the array has the same value. When the values is an immutable value like a number that doesn't really matter but when you fill with a mutable value like an object, as you are doing here, it means that every element is the *same* object which means that changing one of them changes them all because they're all the same. I.e. it's like you did this:

```javascript
const obj = { num: 0 };
const objects = [ obj, obj ];
objects[0].num = 1;
console.log(objects[0].num) // prints 1, no surprise
console.log(objects[1].num) // also prints 1, maybe a surprise.
```

If you want to fill an array with similar but different objects, you need to write this:

```javascript
Array(num).fill().map(() => ({ num: false, curC: false }));
```

It's kinda a dumb idiom but it is what it is. I don't have a good explanation for why you need to call `fill` before you call `map` but trust me you do. `Array(num)` makes an array with a length of `num` but it's empty in a way that means you can't `map` over it. I have no idea what the creators of Javascript were thinking of when they made that decision.

2023-03-16 22:32 UTC, SadieBurris commented
do I need to request review every day still? Just checking

2023-03-17 01:40 UTC, gigamonkey approved these changes
I saw things bouncing around your screen today so it looks that that `map` thing was at least part of it.

Yes, keep requesting review. It's how I find the things that have been done. You should feel free to use either the commit message or even a separate comment on the PR to say something about what, if anything, you'd like me to pay attention to when I review the code or questions you may have. Is there something you're stuck on? Or something you suspect there may be a standard way of doing but you don't know what it is? Otherwise I'll just pick something at random to comment on.

2023-03-19 18:10 UTC, gigamonkey requested changes

2023-03-19 18:10 UTC, gigamonkey commented on projects/hopefully-physics/public/script.js
> +        //WHY DO THEY SOMETIMES NOT WANT TO BOUNCE SIDEWAYS COME ON GUYS YOUVE DONE IT BEFORE
Is it because you moved the line above? I'm not sure what you're going for so it's hard to comment on anything except the thing you hate which is how to organize the code to make it more readable which I still believe will make it easier to find bugs.

2023-03-21 21:22 UTC, gigamonkey approved these changes
Sounds from your comments in the code like maybe you have a plan for what comes next.

2023-03-22 20:14 UTC, gigamonkey approved these changes
Keep on going.

2023-03-22 20:14 UTC, gigamonkey commented on projects/hopefully-physics/public/script.js
> +    obs.push({ pos: { x: Math.random() * width, y: Math.random() * height }, r: Math.random() * 40 + 10, a: { x: 0, y: 0.5 }, v: { x: Math.random() * 5, y: 0 }, c: Array(num).fill().map(() => ({ num:
You should really at least break some of these long lines, e.g.:

```javascript
obs.push({
  pos: {
    x: Math.random() * width, 
    y: Math.random() * height
  },
  r: Math.random() * 40 + 10,
  a: { x: 0, y: 0.5 },
  v: { x: Math.random() * 5, y: 0 },
  c: Array(num).fill().map(() => ({ num: false }))
});
```

Also, you may be interested to use a `Set` object for your `c` property: Sets are like mathematical sets; they either contain a thing or they don't. So you could initialize `c` as `c: new Set()` which is an empty set. You can then use `obs[i].c.add(someObject)` to add `someObject` to the set of objects colliding with `obs[i]`. And you can use `obs[i].c.delete(someObject)` to remove it and `obs[i].c.has(someObject)` to test whether it is in the set. Sets are designed to do this kind of lookup very efficiently and also this will make what's going on a bit more obvious.

2023-03-23 03:14 UTC, gigamonkey approved these changes
Glad the `Set` thing at least appealed to you.

2023-03-24 19:54 UTC, gigamonkey approved these changes
In the interest of adding tools to your toolbox, when you decide you want to tighten up `f`, you may find the function `Math.sign` useful. It takes a number and returns -1, 0, or 1 depending on whether the number is less than. equal to, or greater than 0.

That lets you do things like:

```javascript
someValue += Math.sign(anotherValue) * amount;
```

to either add or subtract `amount` to/from `someValue` depending on whether `anotherValue` is positive or negative and get rid of some `if` statements.


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign

2023-03-31 03:42 UTC, gigamonkey approved these changes
Looks good. I like their little vector noses. I wonder if you'd feel better about my code formatting suggestions if I gave you a tool that would just do it automatically. That's actually how professional developers mostly handle it these days—rather than argument about formatting and style, they just all commit to using a standard formatting tool (something a bit more aggressive than the default "Format document") and then avoid a bunch of arguments. If I have a chance tomorrow I'll see if I can show you how to install such a thing into your codespace.

2023-03-31 03:42 UTC, gigamonkey commented on projects/hopefully-physics/public/script.js
> +        //also just so you know I have been doing things but they never work so I delete them... I should commit more
Yeah. I could perhaps give you better help if I saw some of the missteps too.

2023-04-24 21:58 UTC, merged