Assignments/recursion
bhs-intro-to-programming/SadieBurris pull request #37
Opened 2023-04-10 22:31 UTC by SadieBurris

2023-04-11 03:16 UTC, gigamonkey requested changes
Good start! Keep going.

2023-04-11 03:16 UTC, gigamonkey commented on assignments/recursion/code.js
> +    //not done
On the right track. If you trace through a few calls, e.g. start from `fibonacci(2)` and trace what happens in each of the recursive calls, I think you'll see the problem.

2023-04-12 02:38 UTC, gigamonkey requested changes
Good progress. Keep on going!

2023-04-12 02:38 UTC, gigamonkey commented on assignments/recursion/code.js
> +const gcd = (a, b) => b === 0 ? a : gcd(b, a % b)
This kind of compact, concise code I love, btw. So at least we agree on some things.

2023-04-12 02:38 UTC, gigamonkey commented on assignments/recursion/code.js
> +    return sum(ar.slice(1))
This works but is a bit convoluted. Also it's generally considered poor form to mutate an array or object passed into a function if doing so is not an explicit part of the purpose of the function. Can you figure out a way to add `a[0]` to the sum of the rest of the array without jamming it into the array itself?

2023-04-12 02:38 UTC, gigamonkey commented on assignments/recursion/code.js
> +const search = (ar, val) => ar[0] === val ? true : ar.length === 0 ? false : search(ar.slice(1), val)
This probably passes the tests because Javascript is a bit sloppy and will let you evaluate `ar[0]` even when there is no 0th element. But it would be a bit more stylish (and required in more picky languages) to check that the length is not zero before you try to do anything with elements of the array. This also has the advantage of putting the base case first and making it quite clear what it is:

```javascript
const search = (ar, val) => ar.length === 0 ? false : ar[0] === val || search(ar.slice(1), val)
```

And then you could condense that even more if you want to be extra pithy and turn it into a single boolean expression:

```javascript
const search = (ar, val) => ar.length > 0 && (ar[0] === val || search(ar.slice(1), val));
```

2023-04-13 03:28 UTC, gigamonkey requested changes
Gave you a hint for `reverseString`.

2023-04-13 03:28 UTC, gigamonkey commented on assignments/recursion/code.js
> +  //I know how do do just it in a loop but no clue for recusively with just one arguemnt
When we recurse on strings (or arrays) the usual pattern is to peel off the first element, i.e. the first character in a string, and somehow combine it with the result of calling the function recursively on the rest of the string. That isn't always how it works but pretty often. So with that in mind you can ask, where will the first character of the original string end up in the reversed string? And assuming you put in there, what has to happen to the rest of the string to be combined with that character to produce the whole string reversed?

Hopefully that's enough of a hint to get you going but hit me up if you need more.

2023-04-14 02:42 UTC, gigamonkey requested changes
This is kind of the same hint I gave you in class stated maybe a bit more explicitly.

2023-04-14 02:42 UTC, gigamonkey commented on assignments/recursion/code.js
> +    t.right = treeMap(t.right, fn)
This is similar to the problem with your `sum` implementation: you really shouldn't mutate the objects that are passed into your function unless that's explicit purpose of the function. And in this case the function description specifically said "[r]eturn a new tree". So rather than modifying the tree passed in, you should create a new tree at each level.

2023-04-14 02:42 UTC, gigamonkey commented on assignments/recursion/code.js
> +const change = (c, v) => {
Other main hint here (and the big point about recursion) think about how to solve the problem in terms of smaller versions of the problem that are simply combined. For instance, since the job of this function is to return a count of ways of doing something, can you think of how to split the current problem into two smaller problems, one with a smaller amount and one with a smaller number of coins that together cover all the ways of making change for the current amount with the current coins? If so, you can get those to counts via recursive calls, add them together and Bob's your uncle.

2023-04-15 23:51 UTC, gigamonkey requested changes
You should really fix `sum` and `treeMap` to not modify their arguments. In addition to being more correct, you will probably be able to write them in one line in like all the rest.

2023-04-19 01:23 UTC, gigamonkey approved these changes

2023-04-19 01:23 UTC, gigamonkey commented on assignments/recursion/code.js
> +//number is 1. Either you wrote it weird or just explained it weird
Well, in a world where we use zero-based indices, the "first two" items are the ones at index 0 and index 1. So the first element of the sequence is `fibonacci(0)` and has the value 0 and the second is `fibonacci(1)` with the value 1. I'm at least not alone in using this definition:  https://en.wikipedia.org/wiki/Fibonacci_sequence#Definition

2023-04-19 18:53 UTC, SadieBurris commented on assignments/recursion/code.js
> +//number is 1. Either you wrote it weird or just explained it weird
I would argue technically yes in a coding enviorment, however in an enviorment where no one really thinks in a 0 based world, at least it would make more sense for most people to see a different discription. Also that did come across way more agressive than i meant it to, sorry.

2023-04-24 21:57 UTC, merged